### PR TITLE
[rv_plic] verification stage checklist update

### PR DESCRIPTION
**Pull request by cindychip**

### CODE REVIEW

**Comment by cindychip** [comment]
Oops, I did a rebase on this branch. Seems like it causes lots of difference.. Sorry for the inconvenience.

**Comment by eunchan** [comment]
SHould I close this and cherry-pick?

**Comment by cindychip** [comment]
Sure. Whichever way is easier for you.

**Comment by cindychip** [comment]
The commit ID is: 0f8d70d1efcbdfed8cf612406e8984894b92502a
On my branch: https://github.com/cindychip/opentitan/tree/pr_1480

**Comment by eunchan** [comment]
Your change merged to the plic_checklist branch. Thanks!

**Pull request closed without merging**
